# Site settings
title: Zodiac12
email: main@zodiac.io
url: https://mint.solasiaru.com
description: "Zodiac12 is a set of......."
baseurl: ""

# Color settings
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: discord
    url: https://twitter.com/SBootstrap

# Build settings
markdown: kramdown
permalink: pretty
